sudo : required

services :
  - docker

before_install:
  - docker build -t prasadmunna/docker-react -f Dockerfile.dev .

script:
  - docker run rasadmunna/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "my-aws-elasticbeanstalk-app"
  env: "my-env"
  app: "my-aws-elasticbeanstalk-app"
  bucket_name: "-us-west-2-bkjbk12343123bkjb3123"
  bucket_path: "docker"

on:
  branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: "$AWS_SECRET_KEY"
